/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package yazilimMuh;

import static spark.Spark.get;
import static spark.Spark.post;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

import spark.ModelAndView;
import spark.template.mustache.MustacheTemplateEngine;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

// app
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Logger logger = LogManager.getLogger(App.class);
        logger.error("hellooooo");

        get("/compute",
                (rq, rs) -> {
                    Map<String, String> map = new HashMap<String, String>();
                    map.put("result", "not computed yet!");
                    return new ModelAndView(map, "compute.mustache");
                },
                new MustacheTemplateEngine()

        );

        post("/compute", (req, res) -> {
            String Character = req.queryParams("Character");
            java.util.Scanner sc1 = new java.util.Scanner(Character);

            sc1.useDelimiter("[;\r\n]+");

            java.util.ArrayList<String> inputList = new java.util.ArrayList<>();
            while (sc1.hasNext()) {
                String value = sc1.next().replaceAll("\\s", "");
                inputList.add(value);
            }
            sc1.close();
            System.out.println(inputList);

            String input2 = req.queryParams("input2").replaceAll("\\s", "");
            int input2AsInt = Integer.parseInt(input2);

            // boolean result = App.search(inputList, input2AsInt);
            Map<String, Boolean> map = new HashMap<String, Boolean>();
            // map.put("result", result);
            return new ModelAndView(map, "compute.mustache");

        },
                new MustacheTemplateEngine());

    }

    public static boolean search(ArrayList<Integer> array, int e) {
        System.out.print("inside search");
        if (array == null)
            return false;
        for (int elt : array) {
            if (elt == e)
                return true;
        }
        return false;
    }
}