/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package yazilimMuh;

import static spark.Spark.get;
import static spark.Spark.post;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Random;

import spark.ModelAndView;
import spark.template.mustache.MustacheTemplateEngine;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

// app
public class App {
    public String getGreeting() {
        return "Hello from VSCode.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Logger logger = LogManager.getLogger(App.class);
        logger.error("Custom error message.");

        get("/compute",
                (rq, rs) -> {
                    Map<String, String> map = new HashMap<String, String>();
                    map.put("result", "not computed yet!");
                    return new ModelAndView(map, "compute.mustache");
                },
                new MustacheTemplateEngine()

        );

        post("/compute", (req, res) -> {
            String Character = req.queryParams("Character");
            java.util.Scanner sc1 = new java.util.Scanner(Character);

            sc1.useDelimiter("[;\r\n]+");

            java.util.ArrayList<String> inputList = new java.util.ArrayList<>();
            while (sc1.hasNext()) {
                String value = sc1.next().replaceAll("\\s", "");
                inputList.add(value);
            }
            sc1.close();

            String name = req.queryParams("name").replaceAll("\\s", "");
            String lastName = req.queryParams("lastName").replaceAll("\\s", "");
            int userNameLength = Integer.parseInt(req.queryParams("userNameLength").replaceAll("\\s", ""));

            String result = App.generatePassword(inputList, name, lastName, userNameLength);
            Map<String, String> map = new HashMap<String, String>();
            map.put("result", result);
            return new ModelAndView(map, "compute.mustache");

        },
                new MustacheTemplateEngine());

    }

    public static String generatePassword(ArrayList<String> inputList, String name, String lastName,
            int userNameLength) {
        Random rand = new Random();
        String createdUserName = "";
        int length = inputList.size();

        createdUserName += "_" + name.substring(0, 2); // adın ilk iki karakteri
        for (int i = 0; i < length; i++) {
            int randomNumber = rand.nextInt(length);
            createdUserName += inputList.get(randomNumber);
        }
        createdUserName += lastName.substring(lastName.length() - 3); // soyadın son iki harfi
        createdUserName = createdUserName.substring(0, userNameLength);
        return createdUserName;
    }
}